.model small 
.stack 64 
.data 
TIME_AUX2 DB 0  
FIRST_SECOND_READ DW 01H 
.code
MAIN PROC FAR   
    MOV AX,@DATA
    MOV DS,AX 
    
    
TAKE_TIME:  
MOV AH,2CH ;GET THE SYSTEM TIME 
INT 21H ;CH = hour CL = minute DH = second DL = 1/100 seconds 
CMP FIRST_SECOND_READ,1H
JE READ1
JMP CHECK_IF_ITS_TIME


READ1:
MOV TIME_AUX2,DH
ADD TIME_AUX2,10
CMP TIME_AUX2,3BH
JA SUB60
JMP TIS_OKAY
SUB60:
SUB TIME_AUX2,3BH
TIS_OKAY:
MOV FIRST_SECOND_READ,0H

  
CHECK_IF_ITS_TIME : 
CMP DH,TIME_AUX
JE SPAWN_POWERUP
JMP TAKE_TIME
SPAWN_POWERUP:
MOV FIRST_SECOND_READ,1   
MOV AH,2
MOV DL,'X'
INT 21H
JMP TAKE_TIME

 
    
    
    
    MAIN ENDP 
END MAIN