;INCLUDE ALLMACROS.INC
.MODEL LARGE
.STACK 64
.DATA 
MESS1 DB "*To start chatting press F2$"
MESS2 DB "*To start Galaxy War game press F3$"
MESS3 DB "*To end the program press ESC$" 
MESS4 DB "Enter player (1) name: $"
MESS5 DB "Enter player (2) name: $"
MESS6 DB "GAME IS PAUSED, PRESS ENTER TO CONTINUE$" 
MESS7 DB " WINSSSS!!!!! $"
MESS8 DB " WINSSSS!!!!! $"
MESS9 DB "                                       $" 
MESS10 DB 80D DUP (0DCH),"$"
PSHAPE DB 0DBH
P1NAME DB 15 DUP(?) 
P2NAME DB 15 DUP(?)
BORDER DB 80 DUP("-"),"$" 
P1POS DW 1526H
P2POS DW 0326H 
P1HEALTH DB 20D
P2HEALTH DB 20D
P1BPOS DW 5 DUP (0FFFFH)
P2BPOS DW 5 DUP (0FFFFH) 
HLTA DB "THE APP IS HALTED$"
P1COUNT DB 00H
P2COUNT DB 00H
PU1     DB 00H
PU2     DB 00H 
HEALTH  DB 20D DUP (03), "$"                                        
DELAYER DW 0000H 
APPMODE DB ?
DIRECTION DB "L"
COUNTERHELPER DB 00H
COUNTER DB 00H 
NPUTIME DB 05H
PU1CLEARER DB 07H
PU2CLEARER DB 07H 
PUGEN DB 03,02,01,03,02,01,03,02,01,03,02,01,03,02,01,03,03,02,01,03,02,02,03,02,01,03,02,01,03,02,01,03,03,02,01,03,02,02,03,02,01,03,02,01,03,02,01,03,03,02,01,03,02,02,03,02,01,03,02,01,03,02,01,03,03,02,01,03,02,02,03,02,01,03,02,01,03,02,01,03,03,02,01,03,02,02,03,02,01,03,02,01,03,02,01,03,03,02,01,03,02,02,03,02,01,03,02,01,03,02,01,03
PUIND DB 0FFH  
PUPOS DW 00H
P1WAVEPOS DW 1200H
P2WAVEPOS DW 0600H
.CODE
MAIN PROC 
  MOV AX,@DATA ;MOV ADDRESS OF DATA LOACATION TO AX
  MOV DS,AX    ;MOV ADDRESS OF DATA LOCATION TO DS THROUGH AX



     CALL INTIALIZEAPP

    
     CMP APPMODE,0
     JZ HALT
     CMP APPMODE,1
     JZ GAME
     CMP APPMODE,2
     JZ HALT


     GAME:
     CALL INTIALIZEGAME 
     JMP MOVEPLAYERS    
     PAUSE:
	 CLEARBUFFER          
	 SETCURSOR 0B18H     
     SHOWMESSAGE MESS6  
	 MOV AH, 0H         
	 INT 16H            
	 CMP AH, 1CH         
	 JZ CLEARENTER        
     JMP PAUSE        
     MOVEPLAYERS: 
     JMP POWERSETTER
     MP1:       
     CMP P1HEALTH,0
     JZ PLAYER2WINS
     CMP P2HEALTH,0
     JZ PLAYER1WINS
     MOV AH,1H           
     INT 16H             
     CMP AH,11H          
     JZ FIRE1          
     CMP AH,48H         
     JZ FIRE2            
     CMP AH,20H          
     JZ MOVEP1RIGHT      
     CMP AH,1EH          
     JZ MOVEP1LEFT      
     CMP AH, 4DH        
     JZ MOVEP2RIGHT      
     CMP AH, 4BH         
     JZ MOVEP2LEFT         
     CMP AH, 1CH        
     JZ PAUSE            
     CMP AH,01H         
     JNE CLEARA           
     JMP UPDATEBULLETS   
     JMP MOVEPLAYERS     
;----------------------------------------LEFT RIGHT MOVEMENTS OF PLAYER2------
     MOVEP2RIGHT:
     CLEARBUFFER  
     CMP PU1,1H
     JZ MOVEPLAYERS       
     CMP PU1, 2H
     JNZ NORMALP2RIGHT
     CMP P2POS, 0300H 
     JZ MOVEPLAYERS     
     MOV DIRECTION,"L"
     CALL MOVEPLAYERTWO
     JMP MOVEPLAYERS   
     NORMALP2RIGHT:
     CMP P2POS, 034BH    
     JZ MOVEPLAYERS     
     MOV DIRECTION,"R"
     CALL MOVEPLAYERTWO
     JMP MOVEPLAYERS 
     MOVEP2LEFT:
     CLEARBUFFER
     CMP PU1,1H
     JZ MOVEPLAYERS         
     CMP PU1, 2H
     JNZ NORMALP2LEFT
     CMP P2POS, 034BH   
     JZ MOVEPLAYERS      
      MOV DIRECTION,"R"
     CALL MOVEPLAYERTWO
     JMP MOVEPLAYERS 
     NORMALP2LEFT:
     CMP P2POS, 0300H    
     JZ MOVEPLAYERS      
     MOV DIRECTION,"L"
     CALL MOVEPLAYERTWO
     JMP MOVEPLAYERS      
;----------------------------------------LEFT RIGHT MOVEMENTS OF PLAYER1------     
     MOVEP1RIGHT:
     CLEARBUFFER 
     CMP PU2,1H
     JZ MOVEPLAYERS       
     CMP PU2, 2H
     JNZ NORMALP1RIGHT 
     CMP P1POS,1500H     
     JZ MOVEPLAYERS     
      MOV DIRECTION,"L"    
     CALL MOVEPLAYERONE 
     JMP MOVEPLAYERS      
     NORMALP1RIGHT:
     CMP P1POS,154BH     
     JZ MOVEPLAYERS      
      MOV DIRECTION,"R"    
     CALL MOVEPLAYERONE 
     JMP MOVEPLAYERS      
     MOVEP1LEFT:
     CLEARBUFFER 
     CMP PU2,1H
     JZ MOVEPLAYERS       
     CMP PU2, 2H
     JNZ NORMALP1LEFT
     CMP P1POS,154BH     
     JZ MOVEPLAYERS      
     MOV DIRECTION,"R"    
     CALL MOVEPLAYERONE 
     JMP MOVEPLAYERS      
     NORMALP1LEFT:
     CMP P1POS,1500H     
     JZ MOVEPLAYERS      
     MOV DIRECTION,"L"    
     CALL MOVEPLAYERONE 
     JMP MOVEPLAYERS      
;------------------------------------------------FIRING------------------------     
     FIRE1:   
     CLEARBUFFER    
     CMP PU2,1H
     JZ MOVEPLAYERS     

     CALL DRAWBULLETONE
      
                  
     JMP MOVEPLAYERS              
     FIRE2: 
     CLEARBUFFER    
     CMP PU1,1H
     JZ MOVEPLAYERS    
     CALL DRAWBULLETTWO 
                     
     JMP MOVEPLAYERS             
;--------------------------------UPADTE BULLETS---------------------------------

     UPDATEBULLETS: 
     INC  DELAYER 
     CMP DELAYER,04FFH  
     JNZ MOVEPLAYERS
     
     INC COUNTERHELPER
     MOV DELAYER,0000H
     CMP COUNTERHELPER,05FH 
     JNZ SKIPTOUPDATE
     MOV COUNTERHELPER,00
     INC COUNTER
     SKIPTOUPDATE:
     CALL UPDATEBULLETONE 
     CALL UPDATEBULLETTWO
     JMP MOVEPLAYERS   
     CLEARA:           
     CLEARBUFFER       
     JMP MOVEPLAYERS   
     CLEARENTER:
     SETCURSOR 0B18H     
     SHOWMESSAGE MESS9 
     JMP MOVEPLAYERS
     PLAYER1WINS: 
     CLEARSCREEN
     SETCURSOR 0C1CH 
     SHOWMESSAGE P1NAME
     SHOWMESSAGE MESS7
     GETKEY
     JMP PLAYER1WINS
     PLAYER2WINS:  
     CLEARSCREEN
     
     SETCURSOR 0C1CH
     SHOWMESSAGE P2NAME
     SHOWMESSAGE MESS8 
     GETKEY
     JMP PLAYER2WINS 
     
     
     
     
     POWERSETTER: 
     MOV BL,COUNTER
     CMP PU1CLEARER,BL
     JNZ SKP1 
     MOV PU1,0
     SKP1: 
     CMP PU2CLEARER,BL
     JNZ SKP2 
     MOV PU2,0
     SKP2:
     
     SETCURSOR 0019H
 
     MOV BL,COUNTER
     ADD BL,"0"
     DISPLAYCHARACTER BL
     MOV BL,COUNTER  
     CMP NPUTIME,BL 
     JNZ MP1
     ADD NPUTIME,05H
     MOV PU1CLEARER,BL
     MOV PU2CLEARER,BL
     ADD PU1CLEARER,02
     ADD PU2CLEARER,02
     MOV BX,0
     MOV BL,PUIND
     POWERUPS PUGEN[BX],PUPOS
     INC PUIND 
     JMP MP1
     


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;DONE;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
HALT:
HLT 
MAIN ENDP 
INTIALIZEAPP PROC 

    CLEARSCREEN               ;CLEARS SCREEN FOR NEXT OUTPUT
    SETCURSOR 0A15H           ;SETS CURSOR 
    SHOWMESSAGE MESS4         ;PRINT FIRST NAME REQUEST MESSAGE
    SETCURSOR 0B15H           ;SETS CURSOR
    MOV BX,OFFSET P1NAME      ;MOV OFFSET OF FIRST PLAYER NAME VARIABLE
    TAKELETTER                ;MACRO THAT TAKES A LETTER ONLY
    MOV [BX],AL               ;MOV THE LETTER TO THE FIRST PLACE OF THE PLAYER NAME              
    DISPLAYCHARACTER AL       ;DISP
    INC BX                    ;MOVE TO NEXT LETTER IN THE NAME
    MOV CL,13                 ;COUNTER FOR THE LOOP
    TAKENAME1:                ;LOOP TO TAKE THE REST OF THE NAME
    GETKEY                    ;MACRO THAT GETS KEY PRESSED
    CMP AH,1CH                ;CMP WITH 'ENTER' 
    JZ ENDTN1                 ;IF ENTER IS PRESSES END LOOP
    MOV [BX], AL              ;MOVS THE LETTER TO MEMORY
    DISPLAYCHARACTER AL       ;DISPLAY TAKEN LETTER
    INC BX                    ;MOVE TO NEXT LETTER IN THE NAME
    DEC CL                    ;DECREMENT COUNTER
    JNZ TAKENAME1             ;JMPS TO TAKE THE NEXT LETTER
    ENDTN1:                   ;ENDING INPUT LOOP 
    MOV [BX],'$'              ;MOVE AN ENDING CHAR TO THE END OF THE NAME 
;------------------------SECOND PLAYER NAME INPUT----------
    CLEARSCREEN               ;CLEARS MAIN SCREEN
    SETCURSOR 0A15H           ;SETS CURSOR 
    SHOWMESSAGE MESS5         ;PRINT SECOND NAME REQUEST MESSAGE
    SETCURSOR 0B15H           ;SETS CURSOR
    MOV BX,OFFSET P2NAME      ;MOV OFFSET OF FIRST PLAYER NAME VARIABLE
    TAKELETTER                ;MACRO THAT TAKES A LETTER ONLY
    MOV [BX],AL               ;MOV THE LETTER TO THE FIRST PLACE OF THE PLAYER NAME              
    DISPLAYCHARACTER AL       ;DISP
    INC BX                    ;MOVE TO NEXT LETTER IN THE NAME
    MOV CL,13                 ;COUNTER FOR THE LOOP
    TAKENAME2:                ;LOOP TO TAKE THE REST OF THE NAME
    GETKEY                    ;MACRO THAT GETS KEY PRESSED
    CMP AH,1CH                ;CMP WITH 'ENTER' 
    JZ ENDTN2                 ;IF ENTER IS PRESSES END LOOP
    MOV [BX], AL              ;MOVS THE LETTER TO MEMORY
    DISPLAYCHARACTER AL       ;DISPLAY TAKEN LETTER
    INC BX                    ;MOVE TO NEXT LETTER IN THE NAME
    DEC CL                    ;DECREMENT COUNTER
    JNZ TAKENAME2             ;JMPS TO TAKE THE NEXT LETTER
    ENDTN2:                   ;ENDING INPUT LOOP 
    MOV [BX],'$'              ;MOVE AN ENDING CHAR TO THE END OF THE NAME  
;---------------------------------------------MAIN MENU--------------------------    
    MOV BX,0
    CLEARSCREEN
    TAKEINPUT: 
    SETCURSOR 0A15H   
    SHOWMESSAGE MESS1  
    SETCURSOR 0C15H   
    SHOWMESSAGE MESS2  
    SETCURSOR 0E15H   
    SHOWMESSAGE MESS3  
    READKEY:          
    GETKEY             
    CMP AH,3CH         
    JNZ SKIP
    MOV APPMODE,0 
    JMP DONE
    SKIP:
    CMP AH,3DH        
    JNZ  SKIP1
    MOV APPMODE,1
    JMP DONE
    SKIP1:          
    CMP AH,01H
    JNZ SKIP2
    MOV APPMODE,2 
    JMP DONE
    SKIP2: 
    JNZ TAKEINPUT
    DONE:
RET
INTIALIZEAPP ENDP
 ;-----------------
INTIALIZEGAME PROC 
     CLEARSCREEN    ;CLEARS SCREEN FOR THE GAME BEGINING
     SETCURSOR 0200H  ;SETS CURSOR AT THE SECOND LINE TO PRINT THE UPPER BORDER
     SHOWMESSAGE BORDER ;PRINTS THE DASH ONCE
     SETCURSOR 1600H
     SHOWMESSAGE BORDER
;-----------------------------------------------PRINT STATUS BARS-------------     
     SETCURSOR 0100H   ;SET THE CURSOR AT THE TOP PART OF THE SCREEN TO START DRAWING    
     SHOWMESSAGE P2NAME  ;SHOW THE SECOND PLAYER NAME
     SETCURSOR 0000H
     CHANGECOLOR 0CH,20D
     SHOWMESSAGE HEALTH
     SETCURSOR 1800H    ;SET THE CURSOR AT THE BOTTOM PART OF THE SCREEN TO START DRAWING
     SHOWMESSAGE P1NAME
     SETCURSOR 1700H
     CHANGECOLOR 0CH,20D
     SHOWMESSAGE HEALTH    ;SHOW THE FIRST PLAYER NAME
;----------------------DRAWS PLAYERS AT THEIR CURRENT LOCATION--------------------------------
     CALL DRAWPLAYERONE
     CALL DRAWPLAYERTWO
RET
INTIALIZEGAME ENDP 
;---------------------------
DRAWPLAYERONE PROC 
 		  PUSH P1POS
		  PUSHA
;-------DRAW DOWN PAD-----------------          
		  SETCURSOR P1POS
		  CHANGECOLOR 09H,5
		  DISPLAYCHARACTER PSHAPE
		  DISPLAYCHARACTER PSHAPE
		  DISPLAYCHARACTER PSHAPE
		  DISPLAYCHARACTER PSHAPE
		  DISPLAYCHARACTER PSHAPE
;------------DRAW MIDDLE CANNON-------		  
		  SUB P1POS,0100H
		  ADD P1POS,0002H
		  SETCURSOR P1POS
		  CHANGECOLOR 0CH,1
		  DISPLAYCHARACTER PSHAPE
;------------------------DRAW RIGHT CANNON----
		  SUB P1POS,0100H
		  ADD P1POS,0002H
		  SETCURSOR P1POS
		  CHANGECOLOR 09H,1
		  DISPLAYCHARACTER PSHAPE
		  ADD P1POS,0100H
		  SETCURSOR P1POS
		  CHANGECOLOR 09H,1
  		  DISPLAYCHARACTER PSHAPE
;------------------------DRAW LEFT CANNON----
		  SUB P1POS,0004H
		  SETCURSOR P1POS
		  CHANGECOLOR 09H,1
		  DISPLAYCHARACTER PSHAPE
		  SUB P1POS,0100H
		  SETCURSOR P1POS
		  CHANGECOLOR 09H,1
  		  DISPLAYCHARACTER PSHAPE
          POPA
		  POP P1POS 		
RET
DRAWPLAYERONE ENDP 
;-----------------------
DRAWPLAYERTWO PROC 
          PUSH P2POS
		  PUSHA
;-------DRAW DOWN PAD-----------------          
		  SETCURSOR P2POS
		  CHANGECOLOR 02H,5
		  DISPLAYCHARACTER PSHAPE
		  DISPLAYCHARACTER PSHAPE
		  DISPLAYCHARACTER PSHAPE
		  DISPLAYCHARACTER PSHAPE
		  DISPLAYCHARACTER PSHAPE
;------------DRAW MIDDLE CANNON-------		  
		  ADD P2POS,0100H
		  ADD P2POS,0002H
		  SETCURSOR P2POS
		  CHANGECOLOR 0EH,1
		  DISPLAYCHARACTER PSHAPE
;------------------------DRAW RIGHT CANNON----
		  ADD P2POS,0100H
		  ADD P2POS,0002H
		  SETCURSOR P2POS
		  CHANGECOLOR 02H,1
		  DISPLAYCHARACTER PSHAPE
		  SUB P2POS,0100H
		  SETCURSOR P2POS
		  CHANGECOLOR 02H,1
  		  DISPLAYCHARACTER PSHAPE
;------------------------DRAW LEFT CANNON----
		  SUB P2POS,0004H
		  SETCURSOR P2POS
		  CHANGECOLOR 02H,1
		  DISPLAYCHARACTER PSHAPE
		  ADD P2POS,0100H
		  SETCURSOR P2POS
		  CHANGECOLOR 02H,1
  		  DISPLAYCHARACTER PSHAPE
          POPA
		  POP P2POS     
RET
DRAWPLAYERTWO ENDP	
;------------------------
DELETEPLAYERONE PROC 
 		  PUSH P1POS
		  PUSHA
;-------DRAW DOWN PAD-----------------          
		  SETCURSOR P1POS
		  CHANGECOLOR 09H,5
		  DISPLAYCHARACTER 00
		  DISPLAYCHARACTER 00
		  DISPLAYCHARACTER 00
		  DISPLAYCHARACTER 00
		  DISPLAYCHARACTER 00
;------------DRAW MIDDLE CANNON-------		  
		  SUB P1POS,0100H
		  ADD P1POS,0002H
		  SETCURSOR P1POS
		  CHANGECOLOR 0CH,1
		  DISPLAYCHARACTER 00
;------------------------DRAW RIGHT CANNON----
		  SUB P1POS,0100H
		  ADD P1POS,0002H
		  SETCURSOR P1POS
		  CHANGECOLOR 09H,1
		  DISPLAYCHARACTER 0
		  ADD P1POS,0100H
		  SETCURSOR P1POS
		  CHANGECOLOR 09H,1
  		  DISPLAYCHARACTER 0
;------------------------DRAW LEFT CANNON----
		  SUB P1POS,0004H
		  SETCURSOR P1POS
		  CHANGECOLOR 09H,1
		  DISPLAYCHARACTER 00
		  SUB P1POS,0100H
		  SETCURSOR P1POS
		  CHANGECOLOR 09H,1
  		  DISPLAYCHARACTER 0
          POPA
		  POP P1POS 		  
RET
DELETEPLAYERONE ENDP 
 ;------------------------------
DELETEPLAYERTWO PROC 
          PUSH P2POS
		  PUSHA
;-------DRAW DOWN PAD-----------------          
		  SETCURSOR P2POS
		  CHANGECOLOR 02H,5
		  DISPLAYCHARACTER 0
		  DISPLAYCHARACTER 0
		  DISPLAYCHARACTER 0
		  DISPLAYCHARACTER 0
		  DISPLAYCHARACTER 0
;------------DRAW MIDDLE CANNON-------		  
		  ADD P2POS,0100H
		  ADD P2POS,0002H
		  SETCURSOR P2POS
		  CHANGECOLOR 0EH,1
		  DISPLAYCHARACTER 0
;------------------------DRAW RIGHT CANNON----
		  ADD P2POS,0100H
		  ADD P2POS,0002H
		  SETCURSOR P2POS
		  CHANGECOLOR 02H,1
		  DISPLAYCHARACTER 0
		  SUB P2POS,0100H
		  SETCURSOR P2POS
		  CHANGECOLOR 02H,1
  		  DISPLAYCHARACTER 0
;------------------------DRAW LEFT CANNON----
		  SUB P2POS,0004H
		  SETCURSOR P2POS
		  CHANGECOLOR 02H,1
		  DISPLAYCHARACTER 0
		  ADD P2POS,0100H
		  SETCURSOR P2POS
		  CHANGECOLOR 02H,1
  		  DISPLAYCHARACTER 0
          POPA
		  POP P2POS 		      
RET
DELETEPLAYERTWO ENDP	
;----------------------		  
MOVEPLAYERONE PROC
PUSHA    
CMP DIRECTION,"L"
JZ LEFT1
CMP DIRECTION,"R"
JZ RIGHT1
JMP HALT1
LEFT1:
CALL DELETEPLAYERONE
SUB P1POS,0001H
CALL DRAWPLAYERONE
JMP HALT1
RIGHT1:
CALL DELETEPLAYERONE
ADD P1POS,0001H
CALL DRAWPLAYERONE
HALT1:
POPA   
RET 
MOVEPLAYERONE ENDP
 ;--------------------------
MOVEPLAYERTWO PROC
PUSHA    
CMP DIRECTION,"L"
JZ LEFT
CMP DIRECTION,"R"
JZ RIGHT
JMP HALT2
LEFT:
CALL DELETEPLAYERTWO
SUB P2POS,0001H
CALL DRAWPLAYERTWO
JMP HALT2
RIGHT:
CALL DELETEPLAYERTWO
ADD P2POS,0001H
CALL DRAWPLAYERTWO
HALT2:
POPA   
RET 
MOVEPLAYERTWO ENDP  
;----------------------------------------
DRAWBULLETONE PROC
   CMP PU1,04H
   JZ HALT3
   CMP PU1,03H
   JZ HLTPU2 
   CMP P1COUNT,0AH
   JZ HALT3
   PUSHA
    MOV BX,0
    MOV BL,P1COUNT
	MOV DX,P1POS
	MOV P1BPOS[BX],DX
	SUB P1BPOS[BX],0300H
    ADD P1BPOS[BX],0002H
	SETCURSOR P1BPOS[BX]
	CHANGECOLOR 0CH,1
    SETCURSOR P1BPOS[BX]
	DISPLAYCHARACTER 0DBH
	INC P1COUNT
	INC P1COUNT
	POPA 
	JMP HALT3
	HLTPU2:
	MOV PU1,04H	
HALT3:	
RET
DRAWBULLETONE ENDP	
;-------------------------
DRAWBULLETTWO PROC
   CMP PU2,04H
   JZ HALT4
   CMP PU2,03H
   JZ HLTPU1
   CMP P2COUNT,0AH
   JZ HALT4
   PUSHA
    MOV BX,0
    MOV BL,P2COUNT
	MOV DX,P2POS
	MOV P2BPOS[BX],DX
	ADD P2BPOS[BX],0300H
    ADD P2BPOS[BX],0002H
	SETCURSOR P2BPOS[BX]
	CHANGECOLOR 0EH,1
    SETCURSOR P2BPOS[BX]
	DISPLAYCHARACTER 0DBH
	INC P2COUNT
	INC P2COUNT
	POPA
	JMP HALT4
	HLTPU1:
	MOV PU2,04H	
HALT4:	
RET
DRAWBULLETTWO ENDP	
;--------------------------	    
UPDATEBULLETONE PROC 
    
PUSHA
CMP PU1,04H
JZ DRAWWAVE1
CMP P1COUNT,00
JZ HALT5
MOV BX,0
MOV SI,BX
MOV BL,P1COUNT
MOV CX,BX
SUB BL,02
MOV DI,BX
SHR CX,1
MAINLOOP:
PUSH CX
MOV BX,0
MOV BL,P1COUNT
SHR BX,1
DRAWAMMO 174BH,BX
MOV DX,P1BPOS[SI]
CMP DX,PUPOS
JNZ SKIPA 
PUSHA
MOV BX,0
MOV BL,PUIND
MOV AL,PUGEN[BX]
MOV PU1,AL
POPA
SKIPA:
CMP DH,004H
JB REACHED
SETCURSOR P1BPOS[SI]
DISPLAYCHARACTER 00H
SUB P1BPOS[SI],0100H
SETCURSOR P1BPOS[SI]
CHANGECOLOR 0CH,1
DISPLAYCHARACTER 0DBH
JMP HALT6
REACHED:
SETCURSOR P1BPOS[SI]
DISPLAYCHARACTER 00
CALL DRAWPLAYERONE
CALL DRAWPLAYERTWO
MOV DX,P1BPOS[SI]
MOV BX,P2POS
;COMPARING THE THE LOCATION OF THE BULLET WITH THE VICTIM PLAYER TO DECREMENT HEALTH
CMP DL,BL
JZ POPBACK
INC BL
CMP DL,BL
JZ POPBACK
INC BL
CMP DL,BL
JZ POPBACK
INC BL
CMP DL,BL
JZ POPBACK
INC BL
CMP DL,BL
JZ POPBACK
JMP GOON
POPBACK:
DEC P2HEALTH
GOON:
MOV BX,P1BPOS[DI]
MOV P1BPOS[SI],BX
SUB P1COUNT,02H
SUB DI,02H
SUB SI,02H
MOV BX,0
MOV BL,P1COUNT
SHR BX,1
DRAWAMMO 174BH,BX
HALT6:
PUSH DX
MOV DX, 0
MOV DL, P2HEALTH
SETCURSOR DX
CHANGECOLOR 00,1
SETCURSOR DX
DISPLAYCHARACTER 03
POP DX
INC SI
INC SI
POP CX
DEC CL
JNZ MAINLOOP

JMP HALT5

DRAWWAVE1:
PUSHA
SETCURSOR P1WAVEPOS
CHANGECOLOR 00H,80D 
SETCURSOR P1WAVEPOS
SHOWMESSAGE MESS10 
SUB P1WAVEPOS,0100H
SETCURSOR P1WAVEPOS 
CHANGECOLOR 0CH,80D 
SETCURSOR P1WAVEPOS 
SHOWMESSAGE MESS10 
POPA
CMP P1WAVEPOS,0300H
JNZ HALT5 
SETCURSOR P1WAVEPOS
CHANGECOLOR 00H,80D 
SETCURSOR P1WAVEPOS
SHOWMESSAGE MESS10 
MOV P1WAVEPOS,1200H
MOV PU1,0
DEC P2HEALTH  

CALL DRAWPLAYERTWO
CALL DRAWPLAYERONE

HALT5:
POPA       
RET
UPDATEBULLETONE ENDP 
;--------------
UPDATEBULLETTWO  PROC
PUSHA     
CMP PU2,04H
JZ DRAWWAVE2
CMP P2COUNT,00
JZ HALT7
MOV BX,0
MOV SI,BX
MOV BL,P2COUNT
MOV CX,BX
SUB BL,02
MOV DI,BX
SHR CX,1
MAINLOOP1:
PUSH CX
MOV BX,0
MOV BL,P2COUNT
SHR BX,1
DRAWAMMO 004BH,BX
MOV DX,P2BPOS[SI]
CMP DX,PUPOS
JNZ SKIPB 
PUSHA
MOV BX,0
MOV BL,PUIND
MOV AL,PUGEN[BX]
MOV PU2,AL
POPA
SKIPB:
CMP DH,014H
JA REACHED1
SETCURSOR P2BPOS[SI]
DISPLAYCHARACTER 00H
ADD P2BPOS[SI],0100H
SETCURSOR P2BPOS[SI]
CHANGECOLOR 0EH,1
DISPLAYCHARACTER 0DBH     
JMP HALT8
REACHED1:
SETCURSOR P2BPOS[SI]
DISPLAYCHARACTER 00
CALL DRAWPLAYERONE
CALL DRAWPLAYERTWO
MOV DX,P2BPOS[SI]
MOV BX,P1POS
;COMPARING THE THE LOCATION OF THE BULLET WITH THE VICTIM PLAYER TO DECREMENT HEALTH
CMP DL,BL
JZ POPBACK1
INC BL
CMP DL,BL
JZ POPBACK1
INC BL
CMP DL,BL
JZ POPBACK1
INC BL
CMP DL,BL
JZ POPBACK1
INC BL
CMP DL,BL
JZ POPBACK1
JMP GOON1
POPBACK1:
DEC P1HEALTH

GOON1:


MOV BX,P2BPOS[DI]
MOV P2BPOS[SI],BX
SUB P2COUNT,02H

SUB DI,02H
SUB SI,02H
MOV BX,0
MOV BL,P2COUNT
SHR BX,1
DRAWAMMO 004BH,BX




 
 

HALT8:
PUSH DX
MOV DX, 0
MOV DL, P1HEALTH
ADD DH, 17H
SETCURSOR DX
CHANGECOLOR 00,1
SETCURSOR DX
DISPLAYCHARACTER 03
POP DX
INC SI
INC SI
POP CX
DEC CL
JNZ MAINLOOP1
JMP HALT7
DRAWWAVE2:
PUSHA
SETCURSOR P2WAVEPOS
CHANGECOLOR 00H,80D 
SETCURSOR P2WAVEPOS
SHOWMESSAGE MESS10 
ADD P2WAVEPOS,0100H
SETCURSOR P2WAVEPOS 
CHANGECOLOR 0EH,80D 
SETCURSOR P2WAVEPOS 
SHOWMESSAGE MESS10 
POPA
CMP P2WAVEPOS,1500H
JNZ HALT7 
SETCURSOR P2WAVEPOS
CHANGECOLOR 00H,80D 
SETCURSOR P2WAVEPOS
SHOWMESSAGE MESS10 
MOV P2WAVEPOS,0500H
MOV PU2,0
DEC P1HEALTH  

CALL DRAWPLAYERTWO
CALL DRAWPLAYERONE

HALT7:
POPA

RET
UPDATEBULLETTWO ENDP 
END MAIN  











